AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda-authorizer

Transform:
- AWS::Serverless-2016-10-31

Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: LambdaAuthorizerExample
      StageName: dev
      TracingEnabled: true
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization
              ValidationExpression: 'Bearer *'
              ReauthorizeEvery: 30
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'Authorization'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: helloWorld.handler
      CodeUri: build/
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Description: A simple hello world function.
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: authorizer.handler
      CodeUri: build/
      MemorySize: 128
      Timeout: 5
      Tracing: Active
      Policies:
        Version: '2012-10-17'
        Statement:
        - Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
          Effect: Allow
          Resource: "*"
